nome = str(input('Nome completo:')).strip()
print('Analisando seu nome...')
print('Seu nome em letras maiusculas é {}'.format(nome.upper()))
print('Seu nome em letras minusculas é {}'.format(nome.lower()))
print('Seu nome completo tem {} letras'.format(len(nome) - nome.count(' ')))
nome_separado = nome.split()
print('Seu primeiro nome tem {} letras'.format(len(nome_separado[0])))
